### ISSUE TITLE
App icons library page: Add ® to the name IBM Plex header

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#809] opened 2020-10-26 14:41 UTC
Header should be  IBM Plex® (legal protection)
https://www.ibm.com/design/language/iconography/app-icons/library/

**Comment by vpicone** [comment] 2020-10-26 23:26
Is this a duplicate of #764?

**Comment by mjabbink** [comment] 2020-10-26 23:59
This is for the header down the page. The other is about the naming in the dropdown

**Closed** 2020-10-27 01:07 UTC
Labels: role: dev 🤖
