### ISSUE TITLE
[IDL] Missing space above principles content

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#502] opened 2020-04-07 22:04 UTC
https://www.ibm.com/design/language/philosophy/principles

please remove “e” from creativity in second line

![Screen Shot 2020-04-07 at 5.03.34 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/29ab2116-d7c0-41b6-ac29-1597a7138233)

**Comment by mjabbink** [comment] 2020-04-07 22:18
There also needs to be more spacing after the intro

@sadekbazaraa can you provide spec


This is currently too tight. Needs more space. 
<img width="997" alt="Screen Shot 2020-04-07 at 5 18 01 PM" src="https://user-images.githubusercontent.com/32881239/78724769-c4a8bc00-78f3-11ea-8382-c54461aa4d88.png">

**Comment by vpicone** [comment] 2020-04-07 22:39
the ecreativity bit is a duplicate of https://github.com/carbon-design-system/design-language-website/issues/477

I think the sentence still doesn’t make sense even without the e though. Might be missing some punctuation?

Leaving this open for the spacing stuff.

**Comment by connor-leech** [comment] 2020-04-07 22:40
PR to address typo: https://github.com/carbon-design-system/design-language-website/pull/503

Unless there is some other copy the intro was supposed to be based on, the most recent I could find was this issue: https://github.com/carbon-design-system/design-language-website/issues/219

I like the copy proposed in the above issue, no reason to change it IMO.

cc @vpicone

**Comment by mjabbink** [comment] 2020-04-08 01:05
Needs @Lori-Mapes to resolve the copy

**Comment by sadekbazaraa** [comment] 2020-04-08 13:21
@mjabbink @vpicone in the original version, we had this spec'd at 80px which follows our typical spacing after anchor links. In cases where we don't have anchor links after the intro paragraph, 80px still seems to work well.

Original spec:

![Screen Shot 2020-04-08 at 9 19 17 AM](https://user-images.githubusercontent.com/33162280/78788840-5529df80-797a-11ea-842e-72d7ead934da.png)

**Closed** 2020-04-09 18:00 UTC
Labels: severity: 1 🚨
