### ISSUE TITLE
Color package updates for accessibility

### ISSUE THREAD

**Issue by LMapes** [carbon-design-system/design-language-website#731] opened 2020-09-21 20:22 UTC
## 

Changes here: https://www.ibm.com/design/language/color#the-palette
-->

1. Step one: update color package with new changes to improve accessibility
2. Step two: update color palette to 2.1
3. Step three: push out BComms to WN on BC and IDL plus Slack
4. etc.

## Additional information

- Notes: Issue created as placeholder for this work per @sadekbazaraa

**Comment by vpicone** [comment] 2020-10-06 16:08
is this a duplicate of https://app.zenhub.com/workspaces/auxiliary-squad-5deea70733c75ceaf1bfacae/issues/carbon-design-system/gatsby-theme-carbon/1018

?

**Comment by LMapes** [comment] 2020-10-06 16:17
@sadekbazaraa Did you need this issue to make the color palette changes on site?

**Comment by LMapes** [comment] 2020-10-06 16:34
@vpicone I think the work that needs to be done on this is covered in this issue: https://github.ibm.com/brand/design-language/issues/192

**Comment by sadekbazaraa** [comment] 2020-10-06 17:14
@vpicone 192 covers the updates regarding the Color page itself. Additional issues that Lori is tracking are on the updates to the What's New page so we can make an announcement.

**Closed** 2020-10-06 18:12 UTC
