### ISSUE TITLE
[Illustration pages - isometric] incorrect next/previous links

### ISSUE THREAD

**Issue by peter-garvin** [carbon-design-system/design-language-website#481] opened 2020-03-24 17:29 UTC
Next and links and the bottom are incorrect on isometric design and production pages

@sadekbazaraa @vpicone 

<img width="1645" alt="Screen Shot 2020-03-24 at 12 27 50 PM" src="https://user-images.githubusercontent.com/47458576/77457694-0b15fb00-6dcb-11ea-99a7-37e1f5f501ba.png">
<img width="1646" alt="Screen Shot 2020-03-24 at 12 28 00 PM" src="https://user-images.githubusercontent.com/47458576/77457698-0c472800-6dcb-11ea-939c-66d0e1436c73.png">

**Comment by vpicone** [comment] 2020-03-24 22:33
duplicate of #447

**Closed by vpicone** 2020-03-24 22:33 UTC
