### ISSUE TITLE
Remove sound icon from browser address field [Safari] — there is no sound on the page

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#767] opened 2020-10-01 00:48 UTC
https://www.ibm.com/design/language/animation/tips-and-techniques/

![Screen Shot 2020-09-30 at 7.38.53 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/fdebcfd0-f4e4-4bd5-9462-d582d9c16e14)

**Comment by vpicone** [comment] 2020-10-10 05:14
@mjabbink Is this still happening? I'm not able to replicate it.

**Comment by vpicone** [comment] 2020-10-12 14:16
Gonna close this for now since I think it was resolved when we added auto play/mute to the page.

**Comment by mjabbink** [comment] 2020-10-12 14:32
This still exists.

**Comment by mjabbink** [comment] 2020-10-12 14:33
see Safari desktop @vpicone

**Comment by sadekbazaraa** [comment] 2020-12-01 14:20
@mjabbink @vpicone I wonder if this is a Safari browser bug that has been fixed by any chance? My Safari seems to be working as intended. When a video with audio is playing, the icon is there, as soon as I pause the video, the icon goes away. Are you still seeing it

**Comment by sadekbazaraa** [comment] 2020-12-08 15:45
@mjabbink did you have any luck after updating Safari?

**Comment by mjabbink** [comment] 2020-12-10 01:35
Sorry, still need to do it.

**Comment by alisonjoseph** [comment] 2021-03-05 15:26
I'm also unable to replicate. Going to close for now.

**Closed by alisonjoseph** 2021-03-05 15:26 UTC
Labels: role: dev 🤖, status: waiting for author's response 💬, type: bug 🐛
