### ISSUE TITLE
[IDL] Philosophy > Point of view Poster image reverted to something wrong

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#532] opened 2020-04-29 17:36 UTC
The poster image should not be the rebus. Not sure how this is happening but we are seeing poster images removed and replaced by blank screens or things we never choose or even considered.

https://www.ibm.com/design/language/philosophy/pov/

@sadekbazaraa can you provide the correct poster image please sir. I cannot remember what it was.

@vpicone Some strange things going on in IDL
— Size change of typetester default sizes
— poster image in 2x Grid animation disappeared
— poster image in Philosophy animation disappeared and was replaced by something we never choose, considered or created.

**Comment by sadekbazaraa** [comment] 2020-04-29 17:58
@mjabbink super strange! That poster image is set in Vimeo where the video is hosted. No idea why it's pulling in something different.

**Comment by mjabbink** [comment] 2020-04-29 19:04
Don’t even know how it’s even possible

**Comment by vpicone** [comment] 2020-05-01 03:36
Do you have a screen shot? Poster is Rebus for me.

**Comment by vpicone** [comment] 2020-05-01 03:40
@mjabbink just make sure there's issues for them and they're on the brand prioritized column, we'll get to them as soon as we can.

**Comment by mjabbink** [comment] 2020-05-01 05:32
Exactly. That was never the poster image, nor was it created or considered by us ever. It’s randomly appeared And replaced original

**Comment by mjabbink** [comment] 2020-05-01 05:33
Don’t remember what the original was but it a grab from the actual animation not a random rebus.

**Comment by mjabbink** [comment] 2020-05-01 05:55
We’re chatting in the issue and in Brand column

**Comment by vpicone** [comment] 2020-05-01 14:29
@mjabbink ah, yeah we don’t have the login credentials for Vimeo. Not sure who does if they’ve changes anything recently. They might have made an account wide poster or something?

**Comment by sadekbazaraa** [comment] 2020-05-01 14:30
Think/guide should be the poster frame. That rebus isn't even a frame from this video anywhere hence the confusion. https://vimeo.com/313055439

![Screen Shot 2020-05-01 at 10 28 06 AM](https://user-images.githubusercontent.com/33162280/80812772-9cc91300-8b96-11ea-8678-9be6a0def328.png)

The only other random thing I saw after looking around in Vimeo is that there was an IBM user experience video that was uploaded 14 days ago using the rebus as a poster. That video has nothing to do with the philosophy video that we uploaded over a year ago.

![Screen Shot 2020-05-01 at 9 29 22 AM](https://user-images.githubusercontent.com/33162280/80812791-aa7e9880-8b96-11ea-8573-235de3118f87.png)

@mjabbink @vpicone

**Comment by vpicone** [comment] 2020-05-01 14:32
@sadekbazaraa just commented above. Looks like someone with the Vimeo credentials might have created an account wide poster or something.

**Comment by sadekbazaraa** [comment] 2020-05-01 14:39
I do have credentials but can safely say that it's not an account wide issue because all of the other videos that are also hosted on Vimeo seem to be just fine. 2x grid for example: https://www.ibm.com/design/language/2x-grid

![Screen Shot 2020-05-01 at 10 37 46 AM](https://user-images.githubusercontent.com/33162280/80813390-f251ef80-8b97-11ea-9282-362320f2748d.png)

@vpicone

**Comment by vpicone** [comment] 2020-05-01 14:40
@sadekbazaraa perhaps a group setting then? Maybe check which group of videos this POV one belongs to. Other than that I’d take it up with Vimeo support.

**Comment by sadekbazaraa** [comment] 2020-05-01 14:47
Weird! I inspected the element on IDL and traced it back to this video which is a duplicate of the other video which was also uploaded a year ago. I have no idea who made this one or how the source video changed from the original link to this one but either way, I can fix it.

![Screen Shot 2020-05-01 at 10 44 31 AM](https://user-images.githubusercontent.com/33162280/80813990-119d4c80-8b99-11ea-86cd-c682306e3dac.png)

**Comment by sadekbazaraa** [comment] 2020-05-01 14:50
@vpicone @mjabbink Fixed! Somebody went in and added this Rebus as the poster frame. I set it back to the original poster frame which was still in the list of options. Weird monkey business!

https://www.ibm.com/design/language/philosophy/pov/

**Comment by vpicone** [comment] 2020-05-01 15:01
Cool! Closing this.

**Closed** 2020-05-01 15:02 UTC
Labels: role: dev 🤖, role: visual 🎨, severity: 2
