### ISSUE TITLE
Pictogram Usage page: remove margin around mini gallery bottom of page

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#292] opened 2019-10-01 01:58 UTC
@alisonjoseph @vpicone Same issue in the mirrored page in Carbon.

<img width="646" alt="Screen Shot 2019-09-30 at 3 09 51 PM" src="https://user-images.githubusercontent.com/32881239/65928847-17457080-e3c5-11e9-9fce-fdbc152dcfbc.png">

<img width="984" alt="Screen Shot 2019-09-30 at 3 09 47 PM" src="https://user-images.githubusercontent.com/32881239/65928848-17457080-e3c5-11e9-843c-1e36c21eb729.png">

**Comment by jnm2377** [comment] 2019-10-23 17:06
@mjabbink @alisonjoseph Is this a duplicate of https://github.com/carbon-design-system/gatsby-theme-carbon/issues/452 since it's using the theme for this? I commented on that issue last week for some clarification. So the image gallery in the theme should **_not_** have a margin for each image? Or is it the gallery as a whole should not have a margin?

**Comment by mjabbink** [comment] 2019-10-23 19:06
Not sure how it was built but the images should be aligned versus the current situation where they seem to be off horizontally. Conrad Ennis can provide an image with specs.

**Comment by conradennis** [comment] 2019-10-23 19:46
@mjabbink @jnm2377  looks like the original specs included another image which might explain why the example in the first screenshot Mike posted is sitting 32px below the others (see bottom screenshot below). 

As for the second example, that's because the image being used is has the same bg color as the current site. When we put together this page we were using a darker bg color so it wasn't an issue. 

I'll link the missing image from the first screenshot and for the second screenshot I'll link an updated image with a different background color. 

image one: https://ibm.box.com/s/gd3n73u7vawxmwxet26jemnqahe0i5ug

![Screen Shot 2019-10-23 at 3 34 42 PM](https://user-images.githubusercontent.com/16782944/67427748-bd426000-f5aa-11e9-9bf1-9c1c3ff49ca9.png)

image two: https://ibm.box.com/s/jnwa0etkpfcz2kc6xycn0rehk6kwzhxi

![Screen Shot 2019-10-23 at 3 41 52 PM](https://user-images.githubusercontent.com/16782944/67428192-aa7c5b00-f5ab-11e9-973a-46eadec0e57b.png)

original specs with old site bg color and missing image:

![Screen Shot 2019-10-23 at 3 43 41 PM](https://user-images.githubusercontent.com/16782944/67428322-e9121580-f5ab-11e9-8664-e48018247535.png)

**Comment by jnm2377** [comment] 2019-10-23 20:27
Ah, I see. So it looks like this isn't actually a bug with the theme, it's a bug with the images, as you pointed out @conradennis. Thanks for the clarification.

First image just has the same bg color:
<img width="1271" alt="Screen Shot 2019-10-23 at 3 21 04 PM" src="https://user-images.githubusercontent.com/32556167/67431176-596b6780-f5a9-11e9-9470-7c8e20a3cfd1.png">

Second image has an extra row for the missing image. It's fixed if we add the image or delete the row.
<img width="734" alt="Screen Shot 2019-10-23 at 3 22 55 PM" src="https://user-images.githubusercontent.com/32556167/67431177-596b6780-f5a9-11e9-93ec-ffe36f9a67e3.png">
<img width="670" alt="Screen Shot 2019-10-23 at 3 24 16 PM" src="https://user-images.githubusercontent.com/32556167/67431178-596b6780-f5a9-11e9-94bc-fadffbdd9e83.png">

Going to close the issue in the Gatsby theme and submit a PR to fix this in the Carbon and IDL sites @mjabbink

**Comment by jnm2377** [comment] 2019-10-24 18:49
Looks like the issue for the second image that isn't showing is related to nested grid: https://github.com/carbon-design-system/gatsby-theme-carbon/issues/450

**Closed** 2019-10-28 16:52 UTC
Labels: priority: medium, type: bug 🐛
